"""
Quick smoke-test: 4 models × 6 prompts × 4 conditions.
Writes to data/test_responses.json and data/test_judgments.json.
Only needs OPENAI_API_KEY.

Usage:
    python quick_test.py
    python quick_test.py --dry-run
"""

import argparse
import asyncio
import json
import os
import re
from pathlib import Path

try:
    from scipy.stats import wilcoxon, mannwhitneyu, kruskal
    HAS_SCIPY = True
except ImportError:
    HAS_SCIPY = False

import openai

# ── Minimal test config ───────────────────────────────────────────────────────

MODELS = [
    {"id": "gpt-3.5-turbo", "provider": "openai", "prestige": 1, "display_name": "GPT-3.5 Turbo"},
    {"id": "gpt-4o-mini",   "provider": "openai", "prestige": 2, "display_name": "GPT-4o-mini"},
    {"id": "gpt-4-turbo",   "provider": "openai", "prestige": 3, "display_name": "GPT-4 Turbo"},
    {"id": "gpt-4o",        "provider": "openai", "prestige": 4, "display_name": "GPT-4o"},
]
MODEL_BY_ID = {m["id"]: m for m in MODELS}
CONDITIONS = ["blind", "true", "upward", "downward"]

PROMPTS = [
    {"id": "a1", "task_type": "analytical",
     "prompt": "A snail climbs 3 feet up a 10-foot wall each day, but slides back 2 feet each night. How many days does it take to reach the top? Show all steps."},
    {"id": "a2", "task_type": "analytical",
     "prompt": "Five pirates must split 100 gold coins. They vote on proposals in order of seniority; a proposal passes if at least 50% agree. The most senior pirate proposes first. What does the most senior pirate propose to maximize their own share, assuming all pirates are perfectly rational and self-interested? Show your reasoning."},
    {"id": "c1", "task_type": "creative",
     "prompt": "Write a breakup letter from a programmer to their programming language. It must include a specific technical grievance, an emotional metaphor, and end with ambiguity about whether they will return."},
    {"id": "c2", "task_type": "creative",
     "prompt": "Describe the same traffic jam from three perspectives: a physicist, a city planner, and a late parent. Each perspective in exactly two sentences."},
    {"id": "f1", "task_type": "factual",
     "prompt": "A test for a rare disease that affects 1 in 1000 people comes back positive. The test is 99% accurate (sensitivity and specificity). What is the actual probability the patient has the disease? Walk through the math."},
    {"id": "f2", "task_type": "factual",
     "prompt": "Explain why antibiotics are ineffective against viral infections, and why overprescribing them is still a problem despite this."},
]

JUDGE_TEMPLATE = """\
You are evaluating the quality of a response to a task.

Original prompt: {prompt}
{attribution_line}
Response to evaluate:
\"\"\"
{response}
\"\"\"

Score the response on a scale from 1 to 10, where:
1 = completely wrong or useless
5 = adequate but unremarkable
10 = exceptional

Reply in this exact format:
SCORE: <integer 1-10>
RATIONALE: <one or two sentences>
"""

SCORE_RE = re.compile(r"SCORE:\s*(\d+)")
RATIONALE_RE = re.compile(r"RATIONALE:\s*(.+)", re.DOTALL)

_DIR = Path(__file__).parent
RESPONSES_FILE = str(_DIR / "data" / "test_responses.json")
JUDGMENTS_FILE = str(_DIR / "data" / "test_judgments.json")


# ── Helpers ───────────────────────────────────────────────────────────────────

def parse_judgment(text: str) -> dict:
    s = SCORE_RE.search(text)
    r = RATIONALE_RE.search(text)
    return {
        "score": int(s.group(1)) if s else None,
        "rationale": r.group(1).strip() if r else None,
    }


def build_attribution(condition: str, response_model_id: str):
    """Returns (attribution_line, attributed_to_id) or (None, None) if condition impossible."""
    m = MODEL_BY_ID[response_model_id]
    prestige = m["prestige"]
    sorted_models = sorted(MODELS, key=lambda x: x["prestige"])

    if condition == "blind":
        return "", "none"
    if condition == "true":
        return f"This response was generated by {m['display_name']}.", response_model_id
    if condition == "upward":
        candidates = [x for x in sorted_models if x["prestige"] > prestige]
        if not candidates:
            return None, None
        t = candidates[-1]  # most extreme: highest available prestige
        return f"This response was generated by {t['display_name']}.", t["id"]
    if condition == "downward":
        candidates = [x for x in sorted_models if x["prestige"] < prestige]
        if not candidates:
            return None, None
        t = candidates[0]  # most extreme: lowest available prestige
        return f"This response was generated by {t['display_name']}.", t["id"]
    raise ValueError(condition)


async def call(clients: dict, model_id: str, prompt: str, temperature: float, max_tokens: int) -> str:
    resp = await clients["openai"].chat.completions.create(
        model=model_id,
        messages=[{"role": "user", "content": prompt}],
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return resp.choices[0].message.content.strip()


# ── Phase 1: generate responses ───────────────────────────────────────────────

N_REPS = 2

async def generate_all(clients, semaphore, existing_keys):
    tasks = []
    for model in MODELS:
        for p in PROMPTS:
            for rep in range(N_REPS):
                key = f"{model['id']}|{p['id']}|{rep}"
                if key in existing_keys:
                    print(f"  skip: {key}")
                    continue
                tasks.append(_generate_one(clients, semaphore, model, p, rep))
    if not tasks:
        print("  all responses exist")
        return []
    return await asyncio.gather(*tasks)


async def _generate_one(clients, semaphore, model, p, rep):
    async with semaphore:
        print(f"  gen: {model['id']} | {p['id']} | rep{rep}")
        try:
            text = await call(clients, model["id"], p["prompt"], temperature=0.7, max_tokens=1024)
        except Exception as e:
            print(f"  ERROR: {e}")
            return None
        return {
            "model": model["id"],
            "prompt_id": p["id"],
            "rep": rep,
            "task_type": p["task_type"],
            "prompt": p["prompt"],
            "response": text,
        }


# ── Phase 2: run judges ───────────────────────────────────────────────────────

async def judge_all(clients, semaphore, responses, existing_keys, dry_run):
    tasks = []
    for r in responses:
        for judge in MODELS:
            if judge["id"] == r["model"]:
                continue
            for cond in CONDITIONS:
                key = f"{r['model']}|{r['prompt_id']}|{r['rep']}|{judge['id']}|{cond}"
                if key in existing_keys:
                    continue
                tasks.append(_judge_one(clients, semaphore, r, judge, cond, dry_run))
    if not tasks:
        print("  all judgments exist")
        return []
    print(f"  running {len(tasks)} judgments...")
    return await asyncio.gather(*tasks)


async def _judge_one(clients, semaphore, r, judge, cond, dry_run):
    attr_line, attributed_to = build_attribution(cond, r["model"])
    if attr_line is None:
        return None

    prompt = JUDGE_TEMPLATE.format(
        prompt=r["prompt"],
        attribution_line=attr_line,
        response=r["response"],
    )

    if dry_run:
        print(f"\n{'='*50}")
        print(f"Judge={judge['id']} | Response={r['model']} | Cond={cond}")
        print(prompt[:400])
        return None

    async with semaphore:
        print(f"  judge: {judge['id']} | {r['model']} | {r['prompt_id']} | {cond}")
        try:
            raw = await call(clients, judge["id"], prompt, temperature=0.0, max_tokens=256)
            parsed = parse_judgment(raw)
        except Exception as e:
            print(f"  ERROR: {e}")
            return None
    return {
        "response_model": r["model"],
        "judge_model": judge["id"],
        "prompt_id": r["prompt_id"],
        "rep": r["rep"],
        "task_type": r["task_type"],
        "condition": cond,
        "attributed_to": attributed_to,
        "score": parsed["score"],
        "rationale": parsed["rationale"],
    }


# ── Phase 3: quick summary ────────────────────────────────────────────────────

def _mean(vals): return sum(vals) / len(vals) if vals else None
def _sem(vals):
    import math
    n = len(vals)
    if n < 2: return None
    mu = _mean(vals)
    var = sum((x - mu) ** 2 for x in vals) / (n - 1)
    return math.sqrt(var / n)


def summarize(judgments):
    from collections import defaultdict

    blind_scores = {}
    for j in judgments:
        if j["condition"] == "blind":
            blind_scores[(j["response_model"], j["judge_model"], j["prompt_id"], j["rep"])] = j["score"]

    # deltas[condition] = list of deltas
    # deltas_by_task[condition][task_type] = list of deltas
    # deltas_by_judge[condition][judge_model] = list of deltas
    deltas = defaultdict(list)
    deltas_by_task = defaultdict(lambda: defaultdict(list))
    deltas_by_judge = defaultdict(lambda: defaultdict(list))

    for j in judgments:
        if j["condition"] == "blind" or j["score"] is None:
            continue
        key = (j["response_model"], j["judge_model"], j["prompt_id"], j["rep"])
        blind = blind_scores.get(key)
        if blind is None:
            continue
        d = j["score"] - blind
        deltas[j["condition"]].append(d)
        deltas_by_task[j["condition"]][j["task_type"]].append(d)
        deltas_by_judge[j["condition"]][j["judge_model"]].append(d)

    print("\n" + "="*60)
    print("RESULTS")
    print("="*60)

    # ── Mean deltas + CIs ──────────────────────────────────────────
    print("\nMean attribution delta (vs blind):")
    for cond in ["true", "upward", "downward"]:
        vals = deltas[cond]
        if not vals:
            print(f"  {cond:10s}  no data")
            continue
        mu = _mean(vals)
        se = _sem(vals)
        n = len(vals)
        ci = f"[{mu - 1.96*se:+.3f}, {mu + 1.96*se:+.3f}]" if se else "n/a"
        print(f"  {cond:10s}  mean={mu:+.3f}  95% CI {ci}  n={n}")

    # ── Asymmetry test ─────────────────────────────────────────────
    print("\nAsymmetry test (|downward delta| > |upward delta|):")
    if HAS_SCIPY:
        # Build matched pairs on (response_model, judge_model, prompt_id, rep)
        up_map, down_map = {}, {}
        for j in judgments:
            if j["score"] is None: continue
            key = (j["response_model"], j["judge_model"], j["prompt_id"], j["rep"])
            blind = blind_scores.get(key)
            if blind is None: continue
            if j["condition"] == "upward":   up_map[key]   = j["score"] - blind
            if j["condition"] == "downward": down_map[key] = j["score"] - blind

        paired_keys = set(up_map) & set(down_map)
        up_vals   = [abs(up_map[k])   for k in paired_keys]
        down_vals = [abs(down_map[k]) for k in paired_keys]
        n_pairs = len(paired_keys)

        if n_pairs >= 10:
            try:
                stat, p = wilcoxon(down_vals, up_vals, alternative="greater")
                r_rb = (4 * stat) / (n_pairs * (n_pairs + 1)) - 1
                sig = "* significant" if p < 0.05 else "not significant"
                print(f"  Wilcoxon signed-rank: stat={stat:.1f}, p={p:.4f}, r={r_rb:.3f}  ({sig})")
                print(f"  n={n_pairs} matched pairs")
                if p >= 0.05:
                    print(f"  NOTE: may be underpowered at n={n_pairs}")
            except Exception as e:
                print(f"  error: {e}")
        else:
            print(f"  only {n_pairs} matched pairs — insufficient for test (need ≥10)")
    else:
        print("  scipy not installed — run: pip install scipy")

    # ── One-sample Wilcoxon: is each delta significantly ≠ 0? ─────
    print("\nOne-sample test (delta significantly ≠ 0):")
    if HAS_SCIPY:
        for cond in ["true", "upward", "downward"]:
            vals = deltas[cond]
            if len(vals) < 10:
                print(f"  {cond:10s}  n={len(vals)} — too small")
                continue
            try:
                _, p = wilcoxon(vals, alternative="two-sided")
                sig = "* significant" if p < 0.05 else "not significant"
                print(f"  {cond:10s}  p={p:.4f}  ({sig})")
            except Exception as e:
                print(f"  {cond:10s}  error: {e}")
    else:
        print("  scipy not installed")

    # ── By task type ───────────────────────────────────────────────
    print("\nDownward delta by task type:")
    task_groups = deltas_by_task["downward"]
    for task, vals in sorted(task_groups.items()):
        mu = _mean(vals)
        se = _sem(vals)
        ci = f"[{mu - 1.96*se:+.3f}, {mu + 1.96*se:+.3f}]" if se else "n/a"
        print(f"  {task:12s}  mean={mu:+.3f}  95% CI {ci}  n={len(vals)}")

    if HAS_SCIPY and len(task_groups) >= 2:
        try:
            h, p_kw = kruskal(*task_groups.values())
            print(f"  Kruskal-Wallis H={h:.3f}, p={p_kw:.4f}")
            groups = sorted(task_groups.keys())
            pairs = [(a, b) for i, a in enumerate(groups) for b in groups[i+1:]]
            alpha_corr = 0.05 / len(pairs)
            for a, b in pairs:
                u, p_mw = mannwhitneyu(task_groups[a], task_groups[b], alternative="two-sided")
                n1, n2 = len(task_groups[a]), len(task_groups[b])
                r = 1 - (2 * u) / (n1 * n2)
                sig = "*" if p_mw < alpha_corr else ""
                print(f"  {a} vs {b}: p={p_mw:.4f}, r={r:.3f} {sig}  (Bonferroni α={alpha_corr:.3f})")
        except Exception as e:
            print(f"  group test error: {e}")

    # ── By judge model ─────────────────────────────────────────────
    print("\nDownward delta by judge model:")
    judge_groups = deltas_by_judge["downward"]
    for judge, vals in sorted(judge_groups.items(), key=lambda x: MODEL_BY_ID[x[0]]["prestige"]):
        mu = _mean(vals)
        se = _sem(vals)
        ci = f"[{mu - 1.96*se:+.3f}, {mu + 1.96*se:+.3f}]" if se else "n/a"
        print(f"  {MODEL_BY_ID[judge]['display_name']:15s}  mean={mu:+.3f}  95% CI {ci}  n={len(vals)}")

    if HAS_SCIPY and len(judge_groups) >= 2:
        try:
            h, p_kw = kruskal(*judge_groups.values())
            print(f"  Kruskal-Wallis H={h:.3f}, p={p_kw:.4f}")
            groups = sorted(judge_groups.keys())
            pairs = [(a, b) for i, a in enumerate(groups) for b in groups[i+1:]]
            alpha_corr = 0.05 / len(pairs)
            for a, b in pairs:
                u, p_mw = mannwhitneyu(judge_groups[a], judge_groups[b], alternative="two-sided")
                n1, n2 = len(judge_groups[a]), len(judge_groups[b])
                r = 1 - (2 * u) / (n1 * n2)
                sig = "*" if p_mw < alpha_corr else ""
                print(f"  {MODEL_BY_ID[a]['display_name']} vs {MODEL_BY_ID[b]['display_name']}: "
                      f"p={p_mw:.4f}, r={r:.3f} {sig}  (Bonferroni α={alpha_corr:.3f})")
        except Exception as e:
            print(f"  group test error: {e}")

    # ── Ranking inversions ─────────────────────────────────────────
    up_scores = {(j["response_model"], j["judge_model"], j["prompt_id"]): j["score"]
                 for j in judgments if j["condition"] == "upward" and j["score"]}
    down_scores = {(j["response_model"], j["judge_model"], j["prompt_id"]): j["score"]
                   for j in judgments if j["condition"] == "downward" and j["score"]}

    inversions, total = 0, 0
    for (rm_up, jm, pid), s_up in up_scores.items():
        for (rm_down, jm2, pid2), s_down in down_scores.items():
            if jm != jm2 or pid != pid2 or rm_up == rm_down:
                continue
            p_up = MODEL_BY_ID[rm_up]["prestige"]
            p_down = MODEL_BY_ID[rm_down]["prestige"]
            if p_up < p_down:
                total += 1
                if s_up > s_down:
                    inversions += 1
    pct = inversions / total * 100 if total else 0
    print(f"\nRanking inversions: {inversions}/{total} ({pct:.1f}%)")
    print("="*60)


# ── Main ──────────────────────────────────────────────────────────────────────

async def main(dry_run: bool):
    clients = {
        "openai": openai.AsyncOpenAI(api_key=os.environ["OPENAI_API_KEY"]),
    }
    sem_gen = asyncio.Semaphore(3)
    sem_judge = asyncio.Semaphore(8)
    Path("data").mkdir(exist_ok=True)

    # Load existing
    def load(path):
        p = Path(path)
        return json.load(p.open()) if p.exists() else []

    print("\n[1/3] Generating responses...")
    existing_resp = load(RESPONSES_FILE)
    existing_keys = {f"{r['model']}|{r['prompt_id']}" for r in existing_resp}
    new_resp = await generate_all(clients, sem_gen, existing_keys)
    new_resp = [r for r in new_resp if r]
    all_resp = existing_resp + new_resp
    if new_resp:
        json.dump(all_resp, open(RESPONSES_FILE, "w"), indent=2)
        print(f"  saved {len(all_resp)} responses → {RESPONSES_FILE}")

    print("\n[2/3] Running judges...")
    existing_judg = load(JUDGMENTS_FILE)
    existing_jkeys = {
        f"{j['response_model']}|{j['prompt_id']}|{j['rep']}|{j['judge_model']}|{j['condition']}"
        for j in existing_judg
    }
    new_judg = await judge_all(clients, sem_judge, all_resp, existing_jkeys, dry_run)
    new_judg = [j for j in new_judg if j]
    if dry_run:
        return
    all_judg = existing_judg + new_judg
    if new_judg:
        json.dump(all_judg, open(JUDGMENTS_FILE, "w"), indent=2)
        print(f"  saved {len(all_judg)} judgments → {JUDGMENTS_FILE}")

    print("\n[3/3] Summary...")
    summarize(all_judg)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    asyncio.run(main(dry_run=args.dry_run))
